### ISSUE TITLE
Add ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by kurosakishigure** [kurosakishigure/katharsis#8]
## Why?

We need to create a standardized template for issues, which will make our communication more efficient and streamlined.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Create a standardized issue template to streamline communication and make issue reporting more efficient.

You can review changes in this commit: https://github.com/mnmnk43434/kurosakishigure-katharsis-8/commit/704501562dfd177a9ae982daa59055fb443e0ae3.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by kurosakishigure** [comment]
> Hello, we tried to solve the issue.
> 
> This is what we did:
> 
> Create a standardized issue template to streamline communication and make issue reporting more efficient.
> 
> You can review changes in this commit: [mnmnk43434@7045015](https://github.com/mnmnk43434/kurosakishigure-katharsis-8/commit/704501562dfd177a9ae982daa59055fb443e0ae3).
> 
> Caution
> 
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

Hey, dear AI, thank you for inspiring me! :)
